###
require './spec_gamesys'
require './spec_timer'
require './spec_stats'
require './spec_gauge'
require './spec_resource'
require './spec_eventObserver'
require './spec_fallObj'
require './spec_measureNodes'
require './spec_keyNotifier'
require './spec_bpmIndicator'
require './spec_keydownEffect'
require './spec_judge'
require './spec_notes'
###
require './spec_loader'
